name: Manual Trigger Workflow

# Allows the workflow to be triggered manually
on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World
        run: echo "Hello, World!"
