name: Send Email with HTML Report Attachment

on:
  workflow_dispatch:
    inputs:
      recipient_email:
        description: "Recipient email address"
        required: true

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      # Step to generate the HTML file
      - name: Generate HTML Document
        run: |
          echo "<html><body><h1>Hello from GitHub Actions!</h1><p>This is a dynamically generated HTML file.</p></body></html>" > report.html

      # Step to base64 encode the HTML file without newlines
      - name: Encode HTML Document to Base64
        id: encode
        run: |
          base64 report.html | tr -d '\n' > report_base64.txt

      # Step to log the base64 content for debugging
      - name: Show Base64 Content
        run: |
          echo "Base64 Content:"
          cat report_base64.txt

      # Step to send the email using SendGrid with the HTML report attached
      - name: Send Email with Attachment via SendGrid
        run: |
          base64_content=$(cat report_base64.txt)
          echo "Base64 content length: ${#base64_content}"
          curl -X POST \
          --url https://api.sendgrid.com/v3/mail/send \
          --header "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
          --header 'Content-Type: application/json' \
          --data '{
            "personalizations": [{
              "to": [{"email": "'"${{ github.event.inputs.recipient_email }}"'"}],
              "subject": "HTML Report from GitHub Actions"
            }],
            "from": {"email": "jerry.osorio2aw@gmail.com"},
            "content": [{
              "type": "text/plain",
              "value": "Please find the HTML report attached."
            }],
            "attachments": [{
              "content": "'"$base64_content"'",
              "type": "application/octet-stream",
              "filename": "report.html",
              "disposition": "attachment"
            }]
          }'
