name: Send Email with SendGrid

on:
  workflow_dispatch:
    inputs:
      recipient_email:
        description: "Recipient email address"
        required: true

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Send Email via SendGrid
        run: |
          curl -X POST \
          --url https://api.sendgrid.com/v3/mail/send \
          --header "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
          --header 'Content-Type: application/json' \
          --data '{
            "personalizations": [{
              "to": [{"email": "${{ github.event.inputs.recipient_email }}"}],
              "subject": "Hello from GitHub Actions"
            }],
            "from": {"email": "your-email@example.com"},
            "content": [{
              "type": "text/plain",
              "value": "This is a test email sent from a GitHub Actions workflow."
            }]
          }'
