name: Manual Trigger Workflow

# Allows the workflow to be triggered manually
on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World
        run: echo "Hello, World!"
      - name: Send Email via SendGrid
        run: |
          curl -X POST \
          --url https://api.sendgrid.com/v3/mail/send \
          --header "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
          --header 'Content-Type: application/json' \
          --data '{
            "personalizations": [{
              "to": [{"email": "${{ github.event.inputs.recipient_email }}"}],
              "subject": "Hello from GitHub Actions"
            }],
            "from": {"email": "your-email@example.com"},
            "content": [{
              "type": "text/plain",
              "value": "This is a test email sent from a GitHub Actions workflow."
            }]
          }'
