name: Hello World Workflow

# Run the workflow when pushing code or on pull requests to the main branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      # Step to output "Hello, World!"
      - name: Hello World
        run: echo "Hello, World!"
