name: Send Simple Email with SendGrid

on:
  workflow_dispatch:
    inputs:
      recipient_email:
        description: "Recipient email address"
        required: true

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      # Step to send the email using SendGrid with the HTML report attached
      - name: Send Email with Attachment via SendGrid
        run: |
          base64_content=$(cat report_base64.txt)
          echo "Base64 content length: ${#base64_content}"
          curl -X POST \
          --url https://api.sendgrid.com/v3/mail/send \
          --header "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
          --header 'Content-Type: application/json' \
          --data '{
            "personalizations": [{
              "to": [{"email": "'"${{ github.event.inputs.recipient_email }}"'"}],
              "subject": "HTML Report from GitHub Actions"
            }],
            "from": {"email": "jerry.osorio2aw@example.com"},
            "content": [{
              "type": "text/plain",
              "value": "Please find the HTML report attached."
            }],
            "attachments": [{
              "content": "'"$base64_content"'",
              "type": "text/html",
              "filename": "report.html",
              "disposition": "attachment"
            }]
          }'
