name: Send Simple Email with SendGrid

on:
  workflow_dispatch:
    inputs:
      recipient_email:
        description: "Recipient email address"
        required: true

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      # Step to send a simple email using SendGrid
      - name: Send Simple Email via SendGrid
        run: |
          curl -X POST \
          --url https://api.sendgrid.com/v3/mail/send \
          --header "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
          --header 'Content-Type: application/json' \
          --data '{
            "personalizations": [{
              "to": [{"email": "'"${{ github.event.inputs.recipient_email }}"'"}],
              "subject": "Test Email from GitHub Actions"
            }],
            "from": {"email": "jerry.osorio2aw@gmail.com"},
            "content": [{
              "type": "text/plain",
              "value": "This is a test email."
            }]
          }'
